server:
  port: 8081

spring:
  application:
    name: ai-agent
  data:
    mongodb:
      uri: ${MONGODB_URI}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4
          temperature: 0.7
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:}
      chat:
        options:
          model: claude-3-sonnet-20240229
          temperature: 0.7

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:}
      model-name: gpt-4
      temperature: 0.7
      max-tokens: 2000
  anthropic:
    chat-model:
      api-key: ${ANTHROPIC_API_KEY:}
      model-name: claude-3-sonnet-20240229
      temperature: 0.7
      max-tokens: 2000

agent:
  event-loop:
    thread-pool-size: 10
    queue-capacity: 1000
    polling-interval: 1000
  processing:
    batch-size: 10
    timeout: 30000
    retry-attempts: 3

logging:
  level:
    com.examtopics.aiagent: DEBUG
    dev.langchain4j: DEBUG
    org.springframework.ai: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always