# Nixpacks configuration for Railway deployment
[build]
cmd = "pnpm install --no-frozen-lockfile && pnpm build"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "3000"
NEXT_TELEMETRY_DISABLED = "1"
