name: Frontend (Next.js) Lint

on:
  push:
    branches: [ master, q-labeler ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run ESLint
      run: |
        cd frontend
        npm run lint
    
    - name: Type check with TypeScript
      run: |
        cd frontend
        npx tsc --noEmit
    
    - name: Check for unused dependencies
      run: |
        cd frontend
        npx depcheck || true