name: Telegram Bot (Node.js) Lint

on:
  push:
    branches: [ master, q-labeler ]
    paths:
      - 'telegram-bot/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'telegram-bot/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'telegram-bot/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd telegram-bot
        npm ci
    
    - name: Install ESLint
      run: |
        cd telegram-bot
        npm install --save-dev eslint eslint-config-standard eslint-plugin-node
    
    - name: Create ESLint config
      run: |
        cd telegram-bot
        echo '{
          "extends": ["eslint:recommended", "standard"],
          "env": {
            "node": true,
            "es2022": true
          },
          "parserOptions": {
            "ecmaVersion": 2022,
            "sourceType": "commonjs"
          },
          "rules": {
            "no-console": "off",
            "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }]
          }
        }' > .eslintrc.json
    
    - name: Run ESLint
      run: |
        cd telegram-bot
        npx eslint . --ext .js
    
    - name: Validate Node.js syntax
      run: |
        cd telegram-bot
        npm run validate
    
    - name: Check for unused dependencies
      run: |
        cd telegram-bot
        npx depcheck || true